### ISSUE TITLE
counter-example canvas not aligned with the form

### ISSUE THREAD

**Issue by pascalpoizat** [pascalpoizat/vbpmn#2]
The canvas of the counter example gets out of the limits of the form.
A solution is either to enlarge the form or reduce the size of the counter example canvas.

**Comment by ajaykrishna** [comment]
I have fixed the canvas/window resize issue. Along with it I have been working on isssue #13 . The changes are almost done, except that I am unable to center the display of input LTSs. I haven't checked in the code the repos yet, instead I am sharing updated WAR here to see if there is any other issue. I did some testing using Mozilla Firefox and Chrome. I don't have access to Safari.

I will close #2 and #13 together, once I get the feedback. War attached. 
[transformation.zip](https://github.com/pascalpoizat/vbpmn/files/352422/transformation.zip)

Thanks!

**Comment by pascalpoizat** [comment]
Using Safari Version 9.1.1 (11601.6.17) on OS X 10.11.5. The problem is still there. Further, depending on the zooming (rescaling the page using CMD - and CMD +, I get different relative sizes. See pictures.
![capture d ecran 2016-07-08 a 10 05 07](https://cloud.githubusercontent.com/assets/6471971/16681250/d187c494-44f3-11e6-90d6-03409331fd9a.png)
![capture d ecran 2016-07-08 a 10 04 56](https://cloud.githubusercontent.com/assets/6471971/16681249/d186e4e8-44f3-11e6-84ec-a200dff51135.png)
![capture d ecran 2016-07-08 a 10 04 41](https://cloud.githubusercontent.com/assets/6471971/16681251/d188ff1c-44f3-11e6-8fe9-27e59aa65901.png)

**Comment by ajaykrishna** [comment]
@pascalpoizat Looks like the WAR you are using is not updated one. In the updated WAR, a modal dialog pops up to display input models (changes related to #13 )
Here is the link to the WAR - https://github.com/pascalpoizat/vbpmn/files/352422/transformation.zip

**Comment by ajaykrishna** [comment]
<img width="510" alt="screencap" src="https://cloud.githubusercontent.com/assets/809458/16683302/5cd8c362-44ff-11e6-8b0d-8d39ce6f3f3e.PNG">
Attached screenshot for ref

**Comment by pascalpoizat** [comment]
I downloaded the war from the web page distribution. With the one from the source branch it is ok. However, the popups are not easy to close (at least on my browser) and solving issue #16 becomes very important.

**Comment by pascalpoizat** [comment]
Also you could consider having two buttons (one close to each model file choosing button) rather than a single one.

**Comment by ajaykrishna** [comment]
Thanks for the review. I tried to resize the modal and it doesn't work well enough. So I have changed the implementation, instead I have implemented a `<div>` toggle within the same page to hide/show input LTS models. I am closing this issue and we can further track in #13 #16 

The updated code is available both on site and source repos.
